version: '3.4'

services:
  nginx:
    container_name: FrontFront
    image: nginx:latest
    environment:
      NODE_ENV: production
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - 8000:80
  
  backend:
    container_name: BackBack
    image: music:4
    environment:
      NODE_ENV: production
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./Backend:/Backend
    ports:
      - 5000:5000
